name: Go build

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build-go:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.15
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build -v

      - name: Test
        run: go test -v
